### ISSUE TITLE
runDocker fails on M1 Mac

### ISSUE THREAD

**Issue by lkb2k** [ktorio/ktor-build-plugins#63]
Trying to run runDocker on a Mac with an Apple Silicon cpu fails.  It looks like the build step is picking up the amd64 version of the base image even though the base container eclipse-temurin:17-jre, provides arm64 builds.

> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

How can you override the base image used to build the Docker container?

**Comment by Stexxe** [comment]
I've tested it on an M1 Mac and it works with the warning. Do you have the Docker Desktop installed?
Please leave comments on [this issue](https://youtrack.jetbrains.com/issue/KTOR-5244) in YouTrack.

**Comment by chadselph** [comment]
Jib will use [amd64 by default](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image) no matter what the host machine is running. But since this plugin uses the existing jib tasks, you can just configure it there:

```kotlin
jib.from {
  platforms {
    platform {
      architecture = "arm64"
      os = "linux"
    }
  }
}
```
